### ISSUE TITLE
Stalled project

### ISSUE THREAD

**Issue by RowlandOti** [jasonrogena/scratch_card_reader#3]
This is a great idea. Any attempt at improving it? It's not been maintained for  3 years now. @jasonrogena

**Comment by jasonrogena** [comment]
Hi man. You can definitely pick it up... I'll have make it a Gradle project. I can do that this weekend.

**Comment by RowlandOti** [comment]
@jasonrogena , if you could do so. I'd be willing to take it from there.

**Comment by RowlandOti** [comment]
Any progress?

**Comment by jasonrogena** [comment]
@RowlandOti Sorry dude... Been a bit occupied elsewhere but I'll do this either this or next weekend. You can also try give it a shot then make a pull request

**Comment by RowlandOti** [comment]
Not been updated.

**Comment by RowlandOti** [comment]
Not been updated.
